# Generated by Django 2.2.12 on 2022-08-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('pengarang', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('tahun_terbit', models.IntegerField()),
                ('jumlah_halaman', models.IntegerField()),
                ('jumlah_buku', models.IntegerField()),
                ('kategori', models.CharField(max_length=100)),
            ],
        ),
    ]
